INSERT INTO static.mw_general_rule (general_rule_id, general_rule_desc) VALUES
    ('GR1', 'Classification is primarily based on the titles of section, chapters and sub-chapters but should consider the actual content.'),
    ('GR2', 'Parts and accessories are classified according to the classification of the principal product.'),
    ('GR3', 'If the good can be classified into multiple headings, the most relevant one should be applied.'),
    ('GR4', 'Goods should be classified according to their intended purpose of use.'),
    ('GR5', 'For goods made from multiple products, classification should be made from the material or component that provides essential character.'),
    ('GR6', 'When the rules do not provide clarity, the relevant legal and chapter notes should be consulted.');


INSERT INTO static.mw_general_subrule (general_subrule_id, general_rule_id, general_subrule_desc) VALUES
    ('GR2A', 'GR2', 'Any reference in a heading to an article shall be taken to include a reference to that article incomplete or unfinished, provided that, as presented, the incomplete or unfinished article has the essential character of the complete or finished article. It shall also be taken to include a reference to that article complete or finished (or falling to be classified as complete or finished by virtue of this rule), presented unassembled or disassembled.'),
    ('GR2B', 'GR2', 'Any reference in a heading to a material or substance shall be taken to include a reference to mixtures or combinations of that material or substance with other materials or substances. Any reference to goods of a given material or substance shall be taken to include a reference to goods consisting wholly or partly of such material or substance. The classification of goods consisting of more than one material or substance shall be according to the principles of Rule 3.'),
    ('GR3A', 'GR3', 'The heading which provides the most specific description shall be preferred to headings providing a more general description. However, when two or more headings each refer to part only of the materials or substances contained in mixed or composite goods or to part only of the items in a set put up for retail sale, those headings are to be regarded as equally specific in relation to those goods, even if one of them gives a more complete or precise description of the goods.'),
    ('GR3B', 'GR3', 'Mixtures, composite goods consisting of different materials or made up of different components, and goods put up in sets for retail sale, which cannot be classified by reference to 3 (a), shall be classified as if they consisted of the material or component which gives them their essential character, insofar as this criterion is applicable.'),
    ('GR3C', 'GR3', 'When goods cannot be classified by reference to 3 (a) or 3 (b), they shall be classified under the heading which occurs last in numerical order among those which equally merit consideration'),
    ('GR5A', 'GR5', 'Camera cases, musical instrument cases, gun cases, drawing instrument cases, necklace cases and similar containers, specially shaped or fitted to contain a specific article or set of articles, suitable for longterm use and presented with the articles for which they are intended, shall be classified with such articles when of a kind normally sold therewith.  This Rule does not, however, apply to containers which give the whole its essential character.'),
    ('GR5B', 'GR5', 'Subject to the provisions of Rule 5 (a) above, packing materials and packing containers presented with the goods therein shall be classified with the goods if they are of a kind normally used for packing such goods.  However, this provision is not binding when such packing materials or packing containers are clearly suitable for repetitive use.');
